spring:
  datasource:
    url: jdbc:postgresql://217.76.52.82:5432/texnoera
    username: texnoera
    password: Techn0er@002
    driver-class-name: org.postgresql.Driver
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: texnoera.academy@gmail.com
    password: sjqmzjnzbyxxlusr
    port: 587
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect