spring:
  datasource:
    url: jdbc:postgresql://dpg-cjj94f0cfp5c73eur330-a.frankfurt-postgres.render.com:5432/postgres
    username: postgres
    password: hqymVKaz53SU9sZla8VO6JLUTTLlGN2e
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: texnoera.academy@gmail.com
    password: sjqmzjnzbyxxlusr
    port: 587
  jpa:
    hibernate:
      ddl-auto: update