spring:
  datasource:
    url: ${src/main/resources/.env/POSTGRES_DB_URL}
    username: ${src/main/resources/.env/POSTGRES_DB_USERNAME}
    password: ${src/main/resources/.env/POSTGRES_DB_PASSWORD}
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: texnoera.academy@gmail.com
    password: sjqmzjnzbyxxlusr
    port: 587
  jpa:
    hibernate:
      ddl-auto: update