spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: bucardapp@gmail.com
    password: dzzrhjwijqwjkvoc
    port: 587
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /